name: CI

on: [push]

jobs:
  sast_scan:
    name: Rub bandit scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8

    - name: Install bandir
      run: pip install bandit

    - name: Run bandit scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json
