name: CI

on: [push]

jobs:
  sast_scan:
    name: Rub bandit scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: action/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8

    - name: Install bandir
      run: pip install bandit

    -name: Run bandit scan
      run: bandit -r .
